name: Terraform CI with Terrascan

on:
  push:
    paths:
      - '**.tf'
      - '**.sh'
      - '!.github/workflows/terraformCI.yml'
  pull_request:
    paths:
      - '**.tf'

jobs:
  terraform:
    name: Terraform Format, Validate, Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # You can specify your preferred version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terrascan:
    name: Terrascan Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Terrascan
        run: |
          TERRASCAN_VERSION=$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep tag_name | cut -d '"' -f 4)
          echo "Latest Terrascan version: $TERRASCAN_VERSION"
          
          curl -sL "https://github.com/tenable/terrascan/releases/download/${TERRASCAN_VERSION}/terrascan_Linux_x86_64.tar.gz" -o terrascan.tar.gz

          tar -xzf terrascan.tar.gz terrascan
          sudo mv terrascan /usr/local/bin/
          terrascan version

      
      - name: Run Terrascan
        run: terrascan scan -t terraform -i terraform --non-recursive
